TimeCard/Models/VacationBank.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeCard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VacationBank
    {
        public int Id { get; set; }
        public double VacationHoursPerYear { get; set; }
        public Nullable<double> AccuralVacationHours { get; set; }
        public int PayperiodCount { get; set; }
        public Nullable<int> Is_Authorize { get; set; }
        public int User_Id { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
    
        public virtual User User { get; set; }
    }
}

TimeCard/Controllers/ExcelReportController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Mime;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using TimeCard.BL;
using TimeCard.Helping_Classes;
using TimeCard.Models;

namespace TimeCard.Controllers
{
    public class ExcelReportController : Controller
    {
        SessionDTO sessiondto = new SessionDTO();

        public string GetBaseUrl()
        {
            var request = HttpContext.ApplicationInstance.Request;
            var appUrl = HttpRuntime.AppDomainAppVirtualPath;

            if (appUrl != "/")
                appUrl = "/" + appUrl;

            var baseUrl = string.Format("{0}://{1}{2}",
                request.Url.Scheme, //request.Url.Scheme gives https or http
                request.Url.Authority, //request.Url.Authority gives qawithexperts/com
                appUrl); //appUrl = /questions/111/ok-this-is-url

            return baseUrl; //this will return complete url
        }

        public FileResult DownloadReport(string FileAddress = "")
        {
            //var FileVirtualPath = "~/Content/Medical_Record/" + FileAddress;
            var FileVirtualPath = FileAddress;
            return File(FileVirtualPath, "application/force-download", Path.GetFileName(FileVirtualPath));
        }

        public ActionResult EmployeeEntriesExcelSheet(string ProjectId, string StartDate, string EndDate, string EStatus)
        {
            User user = new UserBL().getUserList().Where(x => x.Id == sessiondto.getId() && x.Is_Authorize == 1).FirstOrDefault();
            List<Project> allprojects = new UserBL().getProjectList().Where(x => x.Is_Authorize == 1).ToList();
            List<EntryTime> allentries = new List<EntryTime>();

            List<ProjectUserCategory> userentries = user.ProjectUserCategories.Where(x => x.User_Id == user.Id).ToList();

            foreach (ProjectUserCategory p in userentries)
            {
                List<EntryTime> enteries = new UserBL().getEntryTimeList().Where(x => x.ProjectUserCategory_Id == p.Id).ToList();
                foreach (EntryTime e in enteries)
                {
                    allentries.Add(e);
                }

            }
            if (StartDate != "")
            {
                DateTime d1 = DateTime.Parse(StartDate);
                allentries = allentries.Where(x => x.Date >= d1.Date && x.Is_Authorize == 1).OrderByDescending(x => x.Date).ToList();

            }
            if (EndDate != "")
            {
                DateTime d2 = DateTime.Parse(EndDate);
                allentries = allentries.Where(x => x.Date <= d2.Date && x.Is_Authorize == 1).OrderByDescending(x => x.Date).ToList();
            }
            if (ProjectId != "")
            {
                allentries = allentries.Where(x => x.ProjectUserCategory.ProjectCategory.Project_Id == Convert.ToInt32(ProjectId) && x.Is_Authorize == 1).OrderByDescending(x => x.Date).ToList();

            }
            if (EStatus == "Pending")
            {
                allentries = allentries.Where(x => x.Is_Approved == 0 && x.Is_Authorize == 1).OrderByDescending(x => x.Date).ToList();
            }
            if (EStatus == "Accepted")
            {
                allentries = allentries.Where(x => x.Is_Approved == 1 && x.Is_Authorize == 1).OrderByDescending(x => x.Date).ToList();
            }
            if (EStatus == "Rejected")
            {
                allentries = allentries.Where(x => x.Is_Approved == 2 && x.Is_Authorize == 1).OrderByDescending(x => x.Date).ToList();
            }

            List<EntriesSearchDTO> entriesdtos = new List<EntriesSearchDTO>();

            foreach (EntryTime e in allentries)
            {
                EntriesSearchDTO edto = new EntriesSearchDTO()
                {
                    Id = e.Id,
                    Name = e.ProjectUserCategory.User.FirstName + ' ' + e.ProjectUserCategory.User.LastName,
                    Hours = e.Hour,
                    Date = e.Date.ToString("MM/dd/yyyy"),
                    LCAT = e.ProjectUserCategory.ProjectCategory.LaborCategory.Name,
                    Project = e.ProjectUserCategory.ProjectCategory.Project.Code
                };
                if (e.Is_Approved == 1)
                {
                    edto.Status = "Accepted";

                }
                if (e.Is_Approved == 0)
                {
                    edto.Status = "Pending";
                }
                if (e.Is_Approved == 2)
                {
                    edto.Status = "Rejected";
                    edto.RejectReason = e.RejectReason;
                }

                entriesdtos.Add(edto);
            }
            entriesdtos = entriesdtos.OrderByDescending(x => x.Date).ToList();

            string path = Server.MapPath("~") + "\\Content\\Excel Reports\\Entries Employee Report (" + DateTime.Now.ToString("MM-dd-yyyy") + ").xlsx";
            ExcelManagement.generateGenericExcelFile(path, entriesdtos);
            return File(path, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Entries Employee Report (" + DateTime.Now.ToString("MM-dd-yyyy") + ").xlsx");

        }

        #region Excel
        /// <summary>
        /// This method is to download the excel sheet with all the employees of the given query.
        /// The reason why these queries are implemented here and not in the separate class is because
        /// they have specific 
        /// </summary>
        /// <param name="fname"></param>
        /// <param name="lname"></param>
        /// <param name="departname"></param>
        /// <param name="divisionName"></param>
        //public ActionResult EntriesExcelSheet(string ProjectId, string StartDate, string EndDate, string EmployeeId, string LaborCategories, string EStatus)
        //{
        //    List<EntryTime> allentries = new UserBL().getEntryTimeList().Where(x => x.Is_Authorize == 1).OrderByDescending(x => x.Date).ToList();
        //    List<User> allusers = new UserBL().getUserList().Where(x => x.Is_Authorize == 1).ToList();
        //    List<Project> allprojects = new UserBL().getProjectList().Where(x => x.Is_Authorize == 1).ToList();

        //    if (StartDate != "")
        //    {
        //        DateTime d1 = DateTime.Parse(StartDate);
        //        allentries = allentries.Where(x => x.Date >= d1.Date).OrderByDescending(x => x.Date).ToList();

        //    }
        //    if (EndDate != "")
        //    {
        //        DateTime d2 = DateTime.Parse(EndDate);
        //        allentries = allentries.Where(x => x.Date <= d2.Date).OrderByDescending(x => x.Date).ToList();
        //    }
        //    if (ProjectId != "")
        //    {
        //        allentries = allentries.Where(x => x.ProjectUserCategory.ProjectCategory.Project_Id == Convert.ToInt32(ProjectId)).OrderByDescending(x => x.Date).ToList();

        //    }
        //    if (EmployeeId != "")
        //    {
        //        allentries = allentries.Where(x => x.ProjectUserCategory.User_Id == Convert.ToInt32(EmployeeId)).OrderByDescending(x => x.Date).ToList();
        //    }
        //    if (LaborCategories != "")
        //    {
        //        allentries = allentries.Where(x => x.ProjectUserCategory.ProjectCategory.LaborCategory_Id == Convert.ToInt32(LaborCategories)).OrderByDescending(x => x.Date).ToList();
        //    }
        //    if (EStatus == "Pending")
        //    {
        //        allentries = allentries.Where(x => x.Is_Approved == 0 && x.Is_Authorize == 1).OrderByDescending(x => x.Date).ToList();
        //    }
        //    if (EStatus == "Accepted")
        //    {
        //        allentries = allentries.Where(x => x.Is_Approved == 1 && x.Is_Authorize == 1).OrderByDescending(x => x.Date).ToList();
        //    }
        //    if (EStatus == "Rejected")
        //    {
        //        allentries = allentries.Where(x => x.Is_Approved == 2 && x.Is_Authorize == 1).OrderByDescending(x => x.Date).ToList();
        //    }

        //    allentries = allentries.Where(x => x.ProjectUserCategory.ProjectCategory.Project.Is_Authorize == 1 && x.ProjectUserCategory.User.Is_Authorize == 1).ToList();

        //    List<EntriesSearchDTO> entriesdtos = new List<EntriesSearchDTO>();

        //    foreach (EntryTime e in allentries)
        //    {
        //        EntriesSearchDTO edto = new EntriesSearchDTO()
        //        {
        //            Id = e.Id,
        //            Name = e.ProjectUserCategory.User.FirstName + ' ' + e.ProjectUserCategory.User.LastName,
        //            Hours = e.Hour,
        //            Project = e.ProjectUserCategory.ProjectCategory.Project.Code,
        //            LCAT = e.ProjectUserCategory.ProjectCategory.LaborCategory.Name,
        //            Date = e.Date.ToString("MM/dd/yyyy")
        //        };
        //        if (e.Is_Approved == 1)
        //        {
        //            edto.Status = "Accepted";

        //        }
        //        if (e.Is_Approved == 0)
        //        {
        //            edto.Status = "Pending";
        //        }
        //        if (e.Is_Approved == 2)
        //        {
        //            edto.Status = "Rejected";
        //            edto.RejectReason = e.RejectReason;
        //        }

        //        entriesdtos.Add(edto);
        //    }
        //    entriesdtos = entriesdtos.OrderByDescending(x => x.Date).ToList();

        //    if (sessiondto.getRole() == 2)
        //    {
        //        string path = Server.MapPath("~") + "\\Content\\Excel Reports\\Entries Admin Report (" + DateTime.Now.ToString("MM-dd-yyyy") + ").xlsx";
        //        ExcelManagement.generateGenericExcelFile(path, entriesdtos);
        //        return File(path, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Entries Admin Report (" + DateTime.Now.ToString("MM-dd-yyyy") + ").xlsx");

        //    }

TimeCard/Views/Home/AddVacationBank.cshtml
@{
    ViewBag.Title = "Add Vacation Bank";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using TimeCard.Models
@using TimeCard.Helping_Classes
@using TimeCard.BL
@{
    SessionDTO sdto = new SessionDTO();
}
<br />
@if (ViewBag.msg != "")
{
    <center><h2><strong>@ViewBag.msg</strong></h2></center>
    <br />
}

<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-offset-2 col-md-8 col-lg-offset-2 col-lg-8">
        <div class="widget-box">
            <div class="widget-header">
                <center><h4 class="widget-title"><strong>Add Vacation Bank</strong></h4></center>
            </div>
            <div class="widget-body">
                <div class="widget-main">
                    <form class="form-horizontal" method="post" action="@Url.Action("PostVacationBank", "Home")">
                        <div>
                            <label>User</label>
                            <select class="form-control" name="User_Id" required>
                                <option value="">Select One</option>
                                @if (ViewBag.userlistcount > 0)
                                {
                                    foreach (User u in ViewBag.userlist)
                                    {
                                        <option value=@u.Id>@u.FirstName&nbsp;@u.LastName</option>
                                    }
                                }
                            </select>
                        </div>
                        <br />
                        <div>
                            <label>Vacation Hours</label>
                            <input type="number" class="form-control" name="VacationHoursPerYear" required />
                        </div>
                        <br />
                        <div class="pull-right">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                        <br /><br /><br />
                    </form>
                </div>
            </div>
        </div>
    </div><!-- /.span -->
</div>

TimeCard/Views/Home/Dashboard.cshtml
@using TimeCard.Models
@using TimeCard.Helping_Classes
@using TimeCard.BL
@{
    SessionDTO sdto = new SessionDTO();
}

@{
    ViewBag.Title = "Dashboard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .square {
        background: #F2F2F2;
        width: 100%;
        height: 100%;
    }

    h1, h2 {
        color: #2a2b6e;
    }

    p {
        color: #5dba47 !important;
    }
</style>

<strong class="text-danger">@ViewBag.Message</strong>
<div class="row">
    <h1><strong>Dashboard</strong></h1>
</div>

@if (sdto.getRole() == 1)
{
    <div class="row">
        <div class="col-lg-offset-3 col-lg-3 col-md-offset-3 col-md-3 col-xs-6">
            <div class="square">
                <br /><br />
                <center><p><strong>Assigned Employees</strong></p></center>
                <br />
                <center><h2>@ViewBag.assignedemployees</h2></center>
            </div>
        </div>
        <div class="col-lg-3 col-md-3 col-xs-6">
            <div class="square">
                <br /><br />
                <center><p><strong>Total Pending Timecards</strong></p></center>
                <br />
                <center><h2>@ViewBag.pendingcard</h2></center>
            </div>
        </div>
    </div>

    if(ViewBag.assignedprojects != 0)
    { 
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-lg-3">
                <div class="square">
                    <br /><br />
                    <center><p><strong>Total Assigned Projects</strong></p></center>
                    <br />
                    <center><h2>@ViewBag.assignedprojects</h2></center>
                </div>
            </div>
        </div>
    }
}
else
{
    <div class="row">
        <div class="col-lg-offset-3 col-lg-3 col-md-offset-3 col-md-3 col-xs-6">
            <div class="square">
                <br /><br />
                <center><p><strong>Total Employees</strong></p></center>
                <br />
                <center><h2>@ViewBag.totalemployees</h2></center>
            </div>
        </div>
        <div class="col-lg-3 col-md-3 col-xs-6">
            <div class="square">
                <br /><br />
                <center><p><strong>Total Managers</strong></p></center>
                <br />
                <center><h2>@ViewBag.totalmanagers</h2></center>
            </div>
        </div>
    </div>
    <br />
    <br />

    <div class="row">
        <div class="col-lg-offset-3 col-lg-3 col-md-offset-3 col-md-3 col-xs-6">
            <div class="square">
                <br /><br />
                <center><p><strong>Total Removed Employees</strong></p></center>
                <br />
                <center><h2>@ViewBag.totalRemovedemployees</h2></center>
            </div>
        </div>
        <div class="col-lg-3 col-md-3 col-xs-6">
            <div class="square">
                <br /><br />
                <center><p><strong>Total Removed Managers</strong></p></center>
                <br />
                <center><h2>@ViewBag.totalRemovedmanagers</h2></center>
            </div>
        </div>
    </div>

    <br />
    <br />
    <div class="row">
        <div class="col-lg-offset-3 col-lg-3 col-md-offset-3 col-md-3 col-xs-6">
            <div class="square">
                <br /><br />
                <center><p><strong>Total Projects</strong></p></center>
                <br />
                <center><h2>@ViewBag.totalprojects</h2></center>
            </div>
        </div>
        <div class="col-lg-3 col-md-3 col-xs-6">
            <div class="square">
                <br /><br />
                <center><p><strong>Total Accepted Time Cards</strong></p></center>
                <br />
                <center><h2>@ViewBag.totalacceptedtimecards</h2></center>
            </div>
        </div>
    </div>
}

TimeCard/Views/Home/EditVacation.cshtml
@{
    ViewBag.Title = "Edit Vacation";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using TimeCard.Models
@using TimeCard.Helping_Classes
@using TimeCard.BL
@{
    SessionDTO sdto = new SessionDTO();
}
<br />
@if (ViewBag.msg != "")
{
    <center><h2><strong>@ViewBag.msg</strong></h2></center>
    <br />
}

<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-offset-2 col-md-8 col-lg-offset-2 col-lg-8">
        <div class="widget-box">
            <div class="widget-header">
                <center><h4 class="widget-title"><strong>Edit Vacation Bank</strong></h4></center>
            </div>
            <div class="widget-body">
                <div class="widget-main">
                    <form class="form-horizontal" method="post" action="@Url.Action("UpdateVacationBank", "Home")">
                        <input type="hidden" name="Id" value="@ViewBag.vacation.Id" />
                        <input type="hidden" class="form-control" name="User_Id" value="@ViewBag.vacation.User_Id" />
                        @{ 
                            string name = ViewBag.vacation.User.FirstName + ' ' + ViewBag.vacation.User.LastName;
                        }
                        <div>
                            <label>User</label>
                            <input type="text" class="form-control" disabled value="@name" />
                        </div>
                        <br />
                        <div>
                            <label>Vacation Hours</label>
                            <input type="number" class="form-control" name="VacationHoursPerYear" value="@ViewBag.vacation.VacationHoursPerYear" required />
                        </div>
                        <br />
                        @*<div>
                            <label>Annual Accural Hours</label>
                            <input type="number" class="form-control" name="AccuralVacationHours" value="@ViewBag.vacation.AccuralVacationHours" />
                        </div>
                        <br />*@
                        <div class="pull-right">
                            <button type="submit" class="btn btn-primary">Update</button>
                        </div>
                        <br /><br /><br />
                    </form>
                </div>
            </div>
        </div>
    </div><!-- /.span -->
</div>

TimeCard/Views/Home/EmployeesVacationBank.cshtml
@{
    ViewBag.Title = "Employees Vacation Bank";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using TimeCard.Models
@using TimeCard.Helping_Classes
@{
    SessionDTO sdto = new SessionDTO();
}
<style>
    h3, h4 {
        color: #2a2b6e;
    }
</style>
<div class="row">
    <div class="col-xs-12">
        <h3 class="header"><strong>List of Employee</strong></h3>
        <div class="clearfix">
            <div class="pull-right tableTools-container"></div>
        </div>
        <!-- div.table-responsive -->
        <!-- div.dataTables_borderWrap -->
        <div class="table-responsive" style="background-color:#EFF3F8;">
            <table id="example" class="display table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Email</th>
                        <th>Phone Mail</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (User user in ViewBag.AssignedEmployees)
                    {
                        <tr>
                            <td>@user.FirstName</td>
                            <td>@user.LastName</td>
                            <td>@user.Email</td>
                            <td>@user.PhoneMail</td>

                            <td>
                                &nbsp; <a class="green" href="@Url.Action("VacationBank","Home", new { User_Id = StringCipher.Base64Encode(user.Id.ToString()) })">
    <i class="ace-icon fa fa-info-circle bigger-160"> </i> &nbsp;&nbsp;&nbsp; View Vacation Bank
</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

TimeCard/Views/Home/ProjectBudgetStatus.cshtml
@{
    ViewBag.Title = "ProjectBudgetStatus";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using TimeCard.Models
@using TimeCard.Helping_Classes
@using TimeCard.BL
@{
    SessionDTO sdto = new SessionDTO();
}
<style>
    h3 {
        color: #2a2b6e;
    }

    #addbtn {
        font-size: 17px;
        color: #2a2b6e;
    }

    #box {
        background-color: #0005a7;
        padding: 20px;
        width: 200px;
        height: 60px;
        margin-bottom: 60px;
    }

    #boxheading {
        color: white;
    }

    p {
        color: white;
    }

    .control-label {
        color: #0005a7;
    }

    #expandBtn {
        width: 35px;
        height: 35px;
    }

    .SheetBtn {
        display: none;
        color: #0005a7 !important;
        font-size: large;
    }

    .timeSheet {
        display: block;
    }

    @@media only screen and (max-width:400px) {
        .timeSheet {
            display: none;
        }

        .SheetBtn {
            display: contents;
        }
    }
</style>

<div class="row " style=" border:5px solid #424ef4; border-radius:10px; color:white;" id="Sheet">
    <div class="col-xs-12" style="background-color:#0005A7;">

        <form action="@Url.Action("SearchProjectBudgetStatus", "Home")" method="post">
            <div class="row">
                <div class="col-md-2 col-lg-4" style="padding: 20px;">
                    <div class="form-group">
                        <label><strong>*Project Code:</strong></label>
                        <input type="text" id="code" name="Code" class="form-control" value="@ViewBag.code">
                    </div>
                </div>



            </div>
            <div class="row">
                <div style="padding: 20px;">
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary pull-right">Search</button><br />
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="row text-center">
    <button href="#" class="btn btn-sm btn-primary SheetBtn" onclick="ShowTimeSheet()">Show Customer Report</button>
</div>

<div class="row timeSheet">
    <div class="col-xs-12" style="height:auto; padding:5%;">
        <h3 class="header"><strong>Project Budget Report</strong></h3><br />

        @if (sdto.getRole() == 2)
        {
            <div class="clearfix">
                <div class="pull-right tableTools-container">
                    @* <form method="post" action="@Url.Action("ProjectBudgetStatusExcel", "ExcelReport")">*@

                    <input type="hidden" name="Code" id="code" value="@ViewBag.code" />
                    <a type="submit" class="btn btn-primary pull-right" onclick="generatePDF()">Get Excel Sheet</a><br />

                    @*<button type="submit" class="btn btn-primary pull-right">Get Excel Sheet</button><br />*@
                    @*</form>*@
                </div>
            </div>
        }

        <!-- div.table-responsive -->
        <!-- div.dataTables_borderWrap -->
        <div class="table-responsive" style="background-color:#EFF3F8;">
            <table id="myTable" class="display table table-striped table-bordered table-hover">

                @*<thead>
                        <tr>
                            <th>Employee</th>
                            <th>Project</th>
                            <th>LCAT</th>
                            <th>Budget</th>
                            <th>Total Cost</th>
                            <th>Remaining</th>

                        </tr>
                    </thead>
                    <tbody>

                        @foreach (ProjectReportDTO e in ViewBag.ProjectReportList)
                        {

                            <tr>

                                <td>
                                    @e.EmployeeName
                                @if (e.Status != "")
                                {<span style="background-color:red; color:white; padding:1px;"> @e.Status </span>
                            }
                            </td>
                            <td>@e.ProjectName</td>
                            <td>@e.LCAT</td>
                            <td>@e.Budget</td>

                            <td>
                                @{
                                    double cst = e.Cost * e.Hours;
                                }
                                @Math.Round(cst, 2)
                            </td>

                            <td>@e.Remaining %</td>
                        </tr>


                    }*@

                <thead>
                    <tr>
                        <th>Project Code</th>
                        <th>Budget</th>
                        <th>Total Cost</th>
                        <th>Remaining</th>
                        <th class="text-center">Remaining Budget</th>
                    </tr>
                </thead>
                <tbody>
                    @if (sdto.getRole() == 1)
                    {
                        foreach (ProjectBudgetDTO pp in ViewBag.ProjectBudgetList)
                        {
                            foreach (int i in ViewBag.ProjectId)
                            {
                                if (i == pp.Id)
                                {
                                    <tr>
                                        <td>@pp.Code</td>
                                        <td>@pp.Budget</td>
                                        <td>@pp.TotalCost</td>
                                        <td>
                                            @if (Convert.ToDouble(pp.Remaining) < 0)
                                            {
                                                <span style="background-color:red; padding:2px; color: white;">@pp.Remaining %</span>

                                            }
                                            else
                                            {
                                                <span>@pp.Remaining %</span>
                                            }

                                        </td>
                                        <td class="text-center">
                                            @{
                                                double rb = Convert.ToDouble(pp.Budget) - Convert.ToDouble(pp.TotalCost);
                                                if (rb < 0)
                                                {
                                                    <span style="background-color:red; padding:2px; color: white;">@rb</span>
                                                }
                                                else
                                                {
                                                    <span>@rb</span>
                                                }
                                            }
                                        </td>
                                    </tr>
                                }
                            }
                        }
                    }
                    else
                    {
                        foreach (ProjectBudgetDTO pp in ViewBag.ProjectBudgetList)
                        {
                            <tr>
                                <td>@pp.Code</td>
                                <td>@pp.Budget</td>
                                <td>@pp.TotalCost</td>
                                <td>
                                    @if (Convert.ToDouble(pp.Remaining) < 0)
                                    {
                                        <span style="background-color:red; padding:2px; color: white;">@pp.Remaining %</span>
                                    }
                                    else
                                    {
                                        <span>@pp.Remaining %</span>
                                    }
                                </td>
                                <td class="text-center">
                                    @{
                                        double rb = Convert.ToDouble(pp.Budget) - Convert.ToDouble(pp.TotalCost);
                                        if (rb < 0)
                                        {
                                            <span style="background-color:red; padding:2px; color: white;">@rb</span>
                                        }
                                        else
                                        {
                                            <span>@rb</span>
                                        }
                                    }
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>


<!-- DonloadFile Message Modal -->
<div class="modal fade" id="DonloadFileModal" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title" style="color: black; text-align: center;"><strong>Employee Assignments</strong></h4>
            </div>
            <div class="modal-body">
                <p style="color: black; text-align: center;">Your file will be downloaded in a few minutes, check your email Account for the Link!</p>
            </div>
            <div class="modal-footer">

            </div>
        </div>

    </div>
</div>


<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>

<script>
    $(document).ready(function () {
        $('#myTable').DataTable({
            "order": [[3, "desc"]]
        });
    });
</script>


<script>
    function generatePDF() {
        var code = document.getElementById("code").value;
        $.ajax({
            type: 'POST',
            url: "../ExcelReport/AsyncProjectBudgetStatusExcel",
            data: {
                Code: code
            },
            //dataType: "json",
            success: function (data) {
                $("#DonloadFileModal").modal("show");
            },
            error: function () { alert('fail'); }
        });
    }
</script>